language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.julia/artifacts"

notifications:
  email: false

branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - JULIA_NUM_THREADS=2

addons:
  homebrew:
    casks:
    - julia

install:
  - bash .ci/get_julia.sh
  # Option 2 to install dependencies:
  - travis_retry pip3 install -r requirements.txt
  - python3 -c "import asedftk; asedftk.install()"
  # Test dependencies:
  - pip3 install "pytest == 4.3.1"  # Newer version caused segfaults

script:
  - julia -e 'include("asedftk/test_asedftk.jl")'
  - python-jl -m pytest

jobs:
  include:
    - stage: test
      env: BUILD_SDIST=true
      python: 3.6
    - os: osx
      osx_image: xcode11.6
      language: ruby
    # Test option 1 directly from Julia
    - language: julia
      install: julia scripts/setup_asedftk.jl
      script: julia -e 'include("asedftk/test_asedftk.jl")'

deploy:  # Note: This will only deploy sdist on linux!
  skip_cleanup: true
  provider: pypi
  user: "__token__"
  distributions: "sdist bdist_wheel"
  password:
    secure: "lyqPLBvKPfYptEFnU7pZTh3UOa/7EgaMGP1WL7fLy78ws8sgyIyX0L+yE/t7Z7YNrpXNr7yI9zDtasmNsvvYARjpz23Od7jhKgmhJE6ecDkTv9nJAKCUTqwGwzZsCxXKv+wCIhHlQIlBv8NOz4bWHYTDU26O76XC+lk2fDkoFaX6OBjcMOMqD9gfTvF/WB5ne2GHzKCbHAvl77rFjtFLTZaUkGlIESmuw1otk+ARwJK+s6ei6439lQWii7hyEas/CEN6T7TaOKnfiIhF/rEssOUzn89ZyRgPsUp7722THubdjxI9vapLqji20DznbOhPJyJh3eoFDPdiyZXBJcBs/lfpJSyGv+8bivZ43FgP2dKaN5gheSghybfEEvbBL2xMb8Jzzhwwp4b2BhGZge+IcKWZHknP7cBb4WJqVMgKRxfFUCZuIcHPQmy0A3wm+u8kyilgkn3vOsx6aD2i6v6//qpIvPuXsV2b/VyUgldC7uIiZ3jx+PUq4MqxNKFiDfghk/o4dBvP8I/Azin1LFA47NL552u6QYX3PKMrAzb9HEB4u7Baj/cDzD5Q1rUJpBwxf24FKM7V7hiNV+JAmlf6BBcva8bZpayk9T9/nH9kA84uDmms8JnIxa4UhjfZkMH/7ttaT2nmMrZHScKac6dvG9ESc55xBlRht599mSyytWA="
  on:
    tags: true
    all_branches: true
    condition: "$BUILD_SDIST == true"
