name: CI
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron:  '0 4 * * 6'  # Run every Sunday

jobs:
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.5'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: |
            ~/.julia/artifacts
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.cache-name }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
      - name: Build sysimage
        run: |
          python -c 'import asedftk; asedftk.build_sysimage()'
      - name: Run pytest tests
        run: python -m pytest
